site_name: ki-und-kopfarbeit
theme:
  name: material
  features:
    - toc.integrate

nav:
  - Home: index.md
  - Separator:
  - Chatbots richtig nutzen: chatbots-richtig-nutzen.md
  - Lernen mit dem Chatbot: lernen-mit-dem-chatbot.md
  - Wie funktioniert ein Chatbot: wie-funktioniert-ein-chatbot-llm.md
  - Separator:
  - Impressum: impressum.md
  - Datenschutzerkl√§rung: datenschutz.md

